// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOXzSODnfxKS4Thit88ihsFWoITB3M0hk',
    appId: '1:1000922177401:android:73072db7183940176559a8',
    messagingSenderId: '1000922177401',
    projectId: 'homegogomarket',
    storageBucket: 'homegogomarket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7N_vADFeT8g6M3VQEmK27AzWh3GPkTA',
    appId: '1:1000922177401:ios:2e3fd2cf0661dc4c6559a8',
    messagingSenderId: '1000922177401',
    projectId: 'homegogomarket',
    storageBucket: 'homegogomarket.firebasestorage.app',
    androidClientId: '1000922177401-p27fi6c2ml91mtmvefh91k8515gusd8n.apps.googleusercontent.com',
    iosClientId: '1000922177401-mbif9k05v1908j9koj5frcln3lp1i9i1.apps.googleusercontent.com',
    iosBundleId: 'com.homegogomarket.seller.app',
  );

}